### ISSUE TITLE
Segmentation > VTL: clicking anything in the GUI immediately executes the segmentation

### ISSUE THREAD

**Issue by CellKai** [biovoxxel/bv3dbox#1]
Hi, thanks for this great tool! 
I just installed it and noticed that when using Segmentation > VTL, clicking anything in the GUI immediately executes the segmentation.
Can you reproduce this issue? I use Win10, Fiji, with ImageJ v 1.53q

**Comment by biovoxxel** [comment]
Hi @CellKai ,

Thanks for trying out the tool.
What you noticed is actially rather a feature then an issue. I wanted to have immediate output feedback.
However, I also noticed that on bigger 3D images that can be a disadvantage, since you always need to wait for it. 
So, I am open for discussion to change this in a way that once one would like to get the output, there could be something like a refresh button. What do you think would be a good option?

**Comment by CellKai** [comment]
> However, I also noticed that on bigger 3D images that can be a disadvantage, since you always need to wait for it.

I supposed that was happening in my case

> So, I am open for discussion to change this in a way that once one would like to get the output, there could be something like a refresh button. What do you think would be a good option?

yes this sounds good. If possible I think it would be nice if it was to update the current segmentation image.

There is a tool called [Interactive H-watershed from Robert Haase](https://imagej.net/plugins/interactive-watershed) that has an interactive interface like this in Fiji, maybe it can give some ideas as well.

**Comment by biovoxxel** [comment]
As an info in between: I tried to change the GUI in a way that only a "preview" button would update everything, and that runs really nicely but then I figured out that this button is not recorded and therefore breaks macro execution. So, I will need to see if there is a solution for that. The only alternative I would see is to not use IJ2-based dialogs. But that might have other drawbacks. 
So, any additional input is wellcome

**Comment by CellKai** [comment]
Hi, thanks for this very quick updates!
Other than the [Interactive H-watershed from Robert Haase](https://imagej.net/plugins/interactive-watershed), I dont have a further idea at the moment, apologies. I am unfortunately not certain how his plugin deals with updating on the fly and macro-recording.

**Comment by biovoxxel** [comment]
As far as I understand the interactive H-watershed it is basically the same as the maxima method implemented in the Voronoi Threshold Labeler.
