### ISSUE TITLE
Consider GitHub actions and deploy to maven.scijava.org

### ISSUE THREAD

**Issue by imagejan** [biovoxxel/bv3dbox#2]
Hi @biovoxxel, how about adding GitHub actions that build every commit, and deploy a SNAPSHOT jar file to maven.scijava.org?

The scripts [`github-actionify.sh`](https://github.com/scijava/scijava-scripts/blob/main/github-actionify.sh) and [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/main/release-version.sh) can help with that. Let me know if you need assistance.

**Comment by biovoxxel** [comment]
Hey @imagejan,

thanks for the suggestion. Honestly, I have no idea about those workflow things on GitHub, but that sounds good. I will first look into it and get back to you in case of questions or if I get lost completely.
