### ISSUE TITLE
Return Empty Primary / Secondary Table from Object Inspector when no overlap present

### ISSUE THREAD

**Issue by shk44** [biovoxxel/bv3dbox#7]
Hi,

I'm working biovoxxel into a macro to analyze a secondary channel within several primary channels using Object Inspector 2D/3D. I have a macro working fairly well, however sometimes there are no secondary objects present within my primary channel. Normally, this is totally fine, but since my macro attempts to save the primary and secondary results tables for future analysis, it throws an error looking for a results table not there. Would it be possible to return empty Primary and Secondary Results tables (with headers) even when no overlap is present between primary/secondary channels?

Thanks,
Shon

**Comment by biovoxxel** [comment]
Thanks for reporting, I will look into it. It should definitely display something

**Comment by biovoxxel** [comment]
The issue should be solved. Now there will be always both tables even if no objects are found. I did not figure this out since I always tested on images with objects ;-)
Thanks again for reporting that
